/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.petrikainulainen.gradle;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        HelloWorld classUnderTest = new HelloWorld();
        // assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
